[package]
name = "kanbanban"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/luizvbo/kanbanban"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
clap = { version = "4.5.55", features = ["derive"] }
crossterm = "0.29.0"
directories = "6.0.0"
pulldown-cmark = "0.13.0"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"

[dev-dependencies]
tempfile = "3.24.0"

[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.typos.default.extend-words]
ratatui = "ratatui"

[[bin]]
name = "kbb"
path = "src/main.rs"
